version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./TestingHub-Cart-RestAPI.postman_collection.json
          environment: ./environment.json
          globals: ./globals.json
build:
  working_directory: /tmp
  steps:
    - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;
    - store_artifacts:
        path: /tmp/art-1
        destination: artifact-file
    - store_artifacts:
        path: /tmp/artifacts

workflows:
  test:
    jobs:
      - newman-collection-run
 